spring.application.name=EjJPARelaciones
spring.datasource.url=${DB_URL_DEPLOY_SUPABASE}
spring.datasource.username=${DB_USER_NAME_DEPLOY_SUPABASE}
spring.datasource.password=${DB_PASSWORD_DEPLOY_SUPABASE}
spring.jpa.hibernate.ddl-auto=update
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
server.port=8080
#springdoc.override-with-generic-response=false
#springdoc.model-and-view-allowed=false
