spring.application.name=EjJPARelaciones
spring.datasource.url=${DB_URL_POSTG}
spring.datasource.username=${DB_USER_NAME_POSTG}
spring.datasource.password=${DB_PASSWORD_POSTG}
spring.jpa.hibernate.ddl-auto=update
spring.datasource.driver-class-name=org.postgresql.Driver
server.port=8080
springdoc.override-with-generic-response=false
springdoc.model-and-view-allowed=false
